CwoPqsCrosswalk/CwoPqsCrosswalk/Controllers/OfficerController.cs
using CwoPqsCrosswalk.Models;
using Microsoft.AspNetCore.Mvc;

namespace CwoPqsCrosswalk.Controllers
{
    public class OfficerController : Controller
    {
        // 
        // GET: /Officer/

        public IActionResult Index()
        {
            return View(new Officer());
        }
    }
}

CwoPqsCrosswalk/CwoPqsCrosswalk/Views/Shared/Pqs.cshtml
@model CwoPqsCrosswalk.Models.CwoPqs

<div>
    @foreach (var chapter in Model.Sections)
    {
        <h3 class="w3-text-blue">@chapter.Number @chapter.Name</h3>
        int i = 0;
        <div class="w3-container w3-clear w3-cell">
            @foreach (var signature in chapter.Signatures)
            {
                @if (i % 2 == 0)
                {
                    <p>
                        @Html.CheckBoxFor(model => signature.Value)
                        @Html.Label("", signature.Key)
                    </p>
                }
                i++;
            }
        </div>
        i = 0;
        <div class="w3-container w3-clear w3-cell">
            @foreach (var signature in chapter.Signatures)
            {
                @if (i % 2 == 1)
                {
                    <p>
                        @Html.CheckBoxFor(model => signature.Value)
                        @Html.Label("", signature.Key)
                    </p>
                }
                i++;
            }
        </div>
    }
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CwoPqsCrosswalk/CwoPqsCrosswalk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - CWO PQS App</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- CSS Framework Stylesheets -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-indigo.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Internal Stylesheets -->
    <link rel="stylesheet" href="~/css/style.css" />
</head>

<body>
    <!-- Navbar -->
    <div class="w3-top">
        <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
            <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
            <a href="#" class="w3-bar-item w3-button w3-theme-l1">Logo</a>
        </div>
    </div>

    <!-- Sidebar -->
    <nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
            <i class="fa fa-remove"></i>
        </a>
        <h4 class="w3-bar-item"><b>Menu</b></h4>
        <a class="w3-bar-item w3-button w3-hover-black" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        <a class="w3-bar-item w3-button w3-hover-black" asp-area="" asp-controller="Officer" asp-action="Index">Officer</a>
    </nav>

    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

    <!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
    <div class="w3-main" style="margin-left:250px">

        <div class="w3-row w3-padding-64">

            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>

        <footer id="myFooter">
            <div class="w3-container w3-theme-l1 w3-padding-small">
                <p>&copy; 2020 - U.S. Navy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
                <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
            </div>
        </footer>

        <!-- END MAIN -->
    </div>

    <script>
        // Get the Sidebar
        var mySidebar = document.getElementById("mySidebar");

        // Get the DIV with overlay effect
        var overlayBg = document.getElementById("myOverlay");

        // Toggle between showing and hiding the sidebar, and add overlay effect
        function w3_open() {
            if (mySidebar.style.display === 'block') {
                mySidebar.style.display = 'none';
                overlayBg.style.display = "none";
            } else {
                mySidebar.style.display = 'block';
                overlayBg.style.display = "block";
            }
        }

        // Close the sidebar with the close button
        function w3_close() {
            mySidebar.style.display = "none";
            overlayBg.style.display = "none";
        }
    </script>
</body>
</html>